Initial upload to the-big-update branch

diff --git a/apps/AstroMenace/install b/apps/AstroMenace/install
--- a/apps/AstroMenace/install
+++ b/apps/AstroMenace/install
@@ -1,22 +1,14 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
-"${DIRECTORY}/pkg-install" "g++ cmake make ninja-build libsdl2-dev libogg-dev libvorbis-dev libopenal-dev libalut-dev libfreetype6-dev" "$(dirname "$0")" || exit 1
+install_packages g++ cmake make ninja-build libsdl2-dev libogg-dev libvorbis-dev libopenal-dev libalut-dev libfreetype6-dev || exit 1
 
 #download
-rm -rf master.zip astromenace-master/
-wget https://github.com/viewizard/astromenace/archive/refs/heads/master.zip || error 'Failed to download zip!'
-unzip master.zip || error 'Failed to unzip'
-rm -f master.zip
-
+cd ~/.local/share
+rm -rf $(pwd)/master.zip $(pwd)/astromenace/
+wget -O $(pwd)/master.zip https://github.com/viewizard/astromenace/archive/refs/heads/master.zip || error 'Failed to download zip!'
+unzip $(pwd)/master.zip -D $(pwd)/astromenace || error 'Failed to extract'
+rm -f $(pwd)/master.zip
 #build
-cd astromenace-master/
+cd $(pwd)/astromenace/
 cmake . || error 'Failed to run cmake'
 c=nproc
 make || error 'Failed to run make'
@@ -27,8 +19,8 @@ Version=1.1
 Type=Application
 Name=AstroMenace
 Comment=Hardcore 3D space scroll-shooter with spaceship upgrade possibilities.
-Icon=$HOME/astromenace-master/share/astromenace_128.png
-Exec=$HOME/astromenace-master/astromenace
+Icon=$(pwd)/share/astromenace_128.png
+Exec=$(pwd)/astromenace
 Categories=Game;
 Terminal=false
 StartupNotify=true" > ~/.local/share/applications/astromenace.desktop
diff --git a/apps/Box64/install-64 b/apps/Box64/install-64
--- a/apps/Box64/install-64
+++ b/apps/Box64/install-64
@@ -1,19 +1,10 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
-"${DIRECTORY}/pkg-install" "cmake make python3 gcc libc6-dev g++ build-essential" "$(dirname "$0")" || exit 1
+install_packages cmake make python3 gcc libc6-dev g++ build-essential || exit 1
 
 rm -rf ~/box64
-git clone https://github.com/ptitSeb/box64 || error 'Failed to clone box64 repository!'
+git_clone https://github.com/ptitSeb/box64 || error 'Failed to clone box64 repository!'
 cd box64 || error 'Failed to change directory'
 mkdir build; cd build; cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo || error 'Failed to run cmake in "build" directory'
-
 #determine how many threads can run without running out of memory
 if [ $(($(free -bt | tail -1 | awk '{print $2}')-$(free -bt | tail -1 | awk '{print $3}'))) -le 2000000000 ];then
   #less than 2GB of available ram
@@ -34,5 +25,4 @@ if ! sudo systemctl restart systemd-binfmt ;then
   journalctl -xe | cat
   echo "Exiting this script as successful, but consider sending the above errors to Pi-Apps developers."
 fi
-
 exit 0
diff --git a/apps/Box86/install-64 b/apps/Box86/install-64
--- a/apps/Box86/install-64
+++ b/apps/Box86/install-64
@@ -1,47 +1,31 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
-function check-armhf() {
-	ARMHF="$(dpkg --print-foreign-architectures | grep "armhf")"
-}
-
-
-#add armhf architecture (multiarch)
-check-armhf
-if [[ "$ARMHF" == *"armhf"* ]]; then
-	echo "armhf arcitecture already added..."
-else
-	sudo dpkg --add-architecture armhf
-	check-armhf
-	if [[ "$ARMHF" != *"armhf"* ]]; then
-		error "armhf architecture should be added by now, but it isn't!"
-	fi
+if dpkg -l box86 &>/dev/null ;then
+  sudo apt purge -y box86
 fi
+sudo rm -f /etc/apt/sources.list.d/box86.list
+sudo dpkg --add-architecture armhf
 
-#install box86 dependencies
-CODENAME="$(lsb_release -cs)"
-if [[ "${CODENAME}" == "focal" ]]; then
-  "${DIRECTORY}/pkg-install" "libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf libc6:armhf libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf osspd:armhf pulseaudio libjpeg62:armhf libudev1:armhf libgl1-mesa-dev:armhf libsnappy1v5:armhf libx11-dev:armhf libsmpeg0:armhf libboost-filesystem1.67.0:armhf libboost-program-options1.67.0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libmyguiengine3debian1v5:armhf libboost-iostreams1.67.0:armhf  libsdl2-mixer-2.0-0:armhf" "$(dirname "$0")" || exit 1
-elif [[ "${CODENAME}" == "groovy" ]]; then
-  "${DIRECTORY}/pkg-install" "libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf libc6:armhf libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf osspd:armhf pulseaudio libjpeg62:armhf libudev1:armhf libgl1-mesa-dev:armhf libsnappy1v5:armhf libx11-dev:armhf libsmpeg0:armhf libboost-filesystem1.71.0:armhf libboost-program-options1.71.0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libmyguiengine3debian1v5:armhf libboost-iostreams1.71.0:armhf  libsdl2-mixer-2.0-0:armhf" "$(dirname "$0")" || exit 1
-elif [[ "${CODENAME}" == "hirsute" ]]; then
-  "${DIRECTORY}/pkg-install" "libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf libc6:armhf libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf osspd:armhf pulseaudio libjpeg62:armhf libudev1:armhf libgl1-mesa-dev:armhf libsnappy1v5:armhf libx11-dev:armhf libsmpeg0:armhf libboost-filesystem1.74.0:armhf libboost-program-options1.74.0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libmyguiengine3debian1v5:armhf libboost-iostreams1.74.0:armhf  libsdl2-mixer-2.0-0:armhf" "$(dirname "$0")" || exit 1
+install_packages cmake make gcc-arm-linux-gnueabihf python3 gcc libc6-dev g++ build-essential || exit 1
+
+rm -rf ~/box86
+git_clone https://github.com/ptitSeb/box86
+cd box86
+mkdir build; cd build; cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
+#determine how many threads can run without running out of memory
+if [ $(($(free -bt | tail -1 | awk '{print $2}')-$(free -bt | tail -1 | awk '{print $3}'))) -le 2000000000 ];then
+  #less than 2GB of available ram
+  threads=3
 else
-	error "this script can't run on your OS! It HAS to be Ubuntu 20.04, 20.10 or 21.04"
+  #greater than 2GB of available ram
+  threads=5
 fi
+echo "Compiling Box64 with $threads threads..."
+make -j${threads} || error 'Failed to compile'
+sudo make install || error "Failed to run 'sudo make install'!"
 
-sudo rm /etc/apt/sources.list.d/box86.list &>/dev/null
-echo "adding box86 repo..."
-sudo wget https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list -O /etc/apt/sources.list.d/box86.list || error "Failed to download /etc/apt/sources.list.d/box86.list"
-echo "adding key..."
-wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add - || error "Failed to add key to box86 repo!"
-echo "running 'sudo apt update'..."
-sudo apt update || error "Failed to run sudo apt update"
-echo "installing box86..."
-sudo apt install box86 -y || error "Failed to install the box86 package"
+if ! sudo systemctl restart systemd-binfmt ;then
+  echo -e "\nWarning: systemd-binfmt failed to restart. Getting debug info..."
+  echo "Running command: 'systemctl status systemd-binfmt.service'"
+  systemctl status systemd-binfmt.service
+  echo "Still exiting with success, but you will have to manually run all x86 applications with box86 as binfmt isn't there to do it for you."
+fi
diff --git a/apps/Color Emoji font/install b/apps/Color Emoji font/install
--- a/apps/Color Emoji font/install
+++ b/apps/Color Emoji font/install
@@ -1,16 +1,8 @@
 #!/bin/bash
 
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
-cd $HOME
 rm -r ~/tmp &>/dev/null
 mkdir -p ~/tmp
-cd tmp || error "Failed to enter $HOME/tmp directory!"
+cd ~/tmp || error "Failed to enter $HOME/tmp directory!"
 wget https://fontsdata.com/zipdown-segoeuiemoji-132714.htm || error "Failed to download Segoe UI Emoji font!"
 wget https://noto-website.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip || error "Failed to download Noto Color Emoji font!"
 mv zipdown-segoeuiemoji-132714.htm segoeuiemoji.zip
diff --git a/apps/Conky Rings/install b/apps/Conky Rings/install
--- a/apps/Conky Rings/install
+++ b/apps/Conky Rings/install
@@ -1,12 +1,4 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 if [ -f "$HOME/.conkyrc" ]; then
   error "▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
 Another Conky theme is already installed! Uninstall the original app (Or delete $HOME/.conkyrc), then try again.
@@ -14,28 +6,25 @@ Another Conky theme is already installed! Uninstall the original app (Or delete 
 fi
 
 # Get dependencies
-"${DIRECTORY}/pkg-install" "conky-all lua50" "$(dirname "$0")" || exit 1
-
+install_packages conky-all lua50 || exit 1
 #get conkyrc
-wget -O ~/.conkyrc https://raw.githubusercontent.com/Botspot/rpi_conky/master/conky_rings/.conkyrc || error "Failed to get .conkyrc!"
-
+wget -O ~/.conkyrc https://raw.githubusercontent.com/Botspot/rpi_conky/master/conky_rings/.conkyrc || exit 1
 #get fonts to ~/.local/share/fonts
 mkdir -p ~/.local/share/fonts && cd ~/.local/share/fonts || error "Failed to create and enter $HOME/.local/share/fonts folder!"
-wget https://github.com/Botspot/rpi_conky/raw/master/conky_rings/fonts.tar.gz || error "Failed to download the required fonts!"
+wget -O fonts.tar.gz https://github.com/Botspot/rpi_conky/raw/master/conky_rings/fonts.tar.gz || error "Failed to download the required fonts!"
 tar -xvf fonts.tar.gz || error "Failed to extract the required fonts!"
 rm -f fonts.tar.gz || error "Failed to remove fonts archive!"
 #remove unnecessary file extracted from the tar.gz
 rm -f .uuid || error "Failed to delete unnecessary .uuid file!"
 
 #get rings.lua
-echo "Downloading config..."
-wget -O ~/.conky_rings.lua https://raw.githubusercontent.com/Botspot/rpi_conky/master/conky_rings/.conky_rings.lua || error "Failed to download conky-rings.lua!"
+wget -O ~/.conky_rings.lua https://raw.githubusercontent.com/Botspot/rpi_conky/master/conky_rings/.conky_rings.lua || exit 1
 
-echo "Running Conky in background..."
+status "Running Conky in background..."
 #run conky this time
 setsid -f conky -d
 
-echo "Making autostart entry..."
+status "Making autostart entry..."
 #make autostart entry to run it next time
 mkdir -p ~/.config/autostart
 echo "[Desktop Entry]
@@ -45,5 +34,4 @@ Exec=bash -c 'sleep 5;conky -q -d -p 3'
 Terminal=false
 Comment=system monitoring tool.
 Categories=Utility;" > ~/.config/autostart/conky.desktop || error "Failed to create desktop entry!"
-
 exit 0
diff --git a/apps/Cool Retro Term/install b/apps/Cool Retro Term/install
--- a/apps/Cool Retro Term/install
+++ b/apps/Cool Retro Term/install
@@ -1,22 +1,12 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
 # Get dependencies
-"${DIRECTORY}/pkg-install" "build-essential qmlscene qt5-qmake qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtgraphicaleffects qml-module-qtquick-dialogs qml-module-qtquick-localstorage qml-module-qtquick-window2 qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel" "$(dirname "$0")" || exit 1
-
+install_packages build-essential qmlscene qt5-qmake qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtgraphicaleffects qml-module-qtquick-dialogs qml-module-qtquick-localstorage qml-module-qtquick-window2 qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel || exit 1
 # Get CRT from github
-git clone --recursive https://github.com/Swordfish90/cool-retro-term || error "failed to clone repository!"
-
+git_clone --recursive https://github.com/Swordfish90/cool-retro-term || error "failed to clone repository!"
 # Compile
 cd cool-retro-term || error "failed on cd step!"
 qmake || error "failed on qmake step!"
 make -j8 || error "failed on make step!"
-
 cp -rf qmltermwidget/src/qmldir qmltermwidget/lib/kb-layouts qmltermwidget/lib/color-schemes qmltermwidget/src/QMLTermScrollbar.qml qmltermwidget/QMLTermWidget
 
 echo "[Desktop Entry]
diff --git a/apps/Email Checker/install b/apps/Email Checker/install
--- a/apps/Email Checker/install
+++ b/apps/Email Checker/install
@@ -1,19 +1,6 @@
 #!/bin/bash
 
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
-#use the error function often!
-#If a certain command is necessary for installation to continue, then add this to the end of it:
-# || error 'reason'
-#example below:
-
-# Get dependencies
-"${DIRECTORY}/pkg-install" "zenity python3-pip yad" "$(dirname "$0")" || exit 1
+install_packages zenity python3-pip yad || exit 1
 sudo pip3 install imapclient || error "Failed to install imapclient!"
 
 output="$(yad --form --center --width=400 --separator='\n' \
@@ -28,7 +15,6 @@ button=$?
 [ $button -ne 0 ] && error "▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
 User exited.
 ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲"
-
 echo "Output: ${output}EOO"
 
 if [ -d ~/raspi-email-checker ];then
@@ -37,23 +23,18 @@ if [ -d ~/raspi-email-checker ];then
 The checkmail.py script inside may contain a password!\\e[39m"
 fi
 
-git clone https://github.com/Botspot/raspi-email-checker || error 'Failed to clone repository!'
+git_clone https://github.com/Botspot/raspi-email-checker || error 'Failed to clone repository!'
 
 #hostname
 sed -i "s/hostname2replace/$(echo "$output" | sed "1q;d")/g" ~/raspi-email-checker/checkmail.py
-
 #email
 sed -i "s/email2replace/$(echo "$output" | sed "2q;d")/g" ~/raspi-email-checker/checkmail.py
-
 #password
 sed -i "s/password2replace/$(echo "$output" | sed "3q;d")/g" ~/raspi-email-checker/checkmail.py
-
 #mailbox
 sed -i "s/mailbox2replace/$(echo "$output" | sed "4q;d")/g" ~/raspi-email-checker/checkmail.py
-
 #checkinterval
 sed -i "s/checkinterval2replace/$(echo "$output" | sed "5q;d")/g" ~/raspi-email-checker/checkmail.py
-
 #run on boot
 mkdir -p ~/.config/autostart
 echo "[Desktop Entry]
@@ -64,5 +45,4 @@ X-GNOME-Autostart-enabled=true
 Hidden=false
 Icon=$(dirname "$0")/icon-64.png
 NoDisplay=false" > ~/.config/autostart/checkmail.desktop
-
 "${DIRECTORY}/etc/terminal-run" "echo -e 'If checkmail.py throws errors, you may have entered invalid information.\nUse this opportunity to test it out.\nFrom now on, checkmail.py will be run on every boot.' ; sudo python ${HOME}/raspi-email-checker/checkmail.py ; sleep infinity" 'Running Email Checker (checkmail.py)' &
diff --git a/apps/Firefox Rapid Release/install b/apps/Firefox Rapid Release/install
--- a/apps/Firefox Rapid Release/install
+++ b/apps/Firefox Rapid Release/install
@@ -1,18 +1,10 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 # Add repository source to apt sources.list
-echo "Adding ubuntu repository..."
-echo "deb http://ports.ubuntu.com/ubuntu-ports bionic-updates main" | sudo tee /etc/apt/sources.list.d/firefox-ubuntu.list || error "Failed to add repository to sources.list!"
+status "Adding ubuntu repository..."
+echo "deb http://ports.ubuntu.com/ubuntu-ports bionic-updates main" | sudo tee /etc/apt/sources.list.d/firefox-ubuntu.list >/dev/null || error "Failed to add repository to sources.list!"
 
 # Add ubuntu keyring
-echo "Signing ubuntu repository..."
+status "Signing ubuntu repository..."
 sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3B4FE6ACC0B21F32
 if [ $? != 0 ];then
   sudo rm -f /etc/apt/sources.list.d/firefox-ubuntu.list
@@ -20,19 +12,11 @@ if [ $? != 0 ];then
 fi
 
 # Add preferences so the ubuntu repositories don't become your "default" repositories
-echo "Preventing Ubuntu repository from causing apt problems..."
+status "Preventing Ubuntu repository from causing apt problems..."
 sudo wget -O /etc/apt/preferences.d/99bionic-updates https://raw.githubusercontent.com/chunky-milk/pi-bashscripts-files/main/Files/99bionic-updates
 if [ $? != 0 ];then
   sudo rm -f /etc/apt/sources.list.d/firefox-ubuntu.list
   error "wget failed to download 99bionic-updates config file!"
 fi
 
-"${DIRECTORY}/api" apt_lock_wait
-
-echo "Running 'sudo apt update'..."
-sudo apt update || error "Failed to run 'sudo apt update'!"
-
-"${DIRECTORY}/api" apt_lock_wait
-
-echo "Installing Firefox package..."
-sudo apt install -t bionic-updates firefox -y || error "Failed to install firefox!"
+install_packages firefox || exit 1
diff --git a/apps/Lightpad/install-32 b/apps/Lightpad/install-32
--- a/apps/Lightpad/install-32
+++ b/apps/Lightpad/install-32
@@ -1,15 +1,7 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 wget https://github.com/Pi-Apps-Coders/files/raw/main/lightpad_0.0.8rev1_armhf.deb -O ~/lightpad.deb || error "Failed to download lightpad.deb!"
 
-"${DIRECTORY}/pkg-install" "$HOME/lightpad.deb" "$(dirname "$0")" || error 'Failed to install lightpad.deb'
+install_packages $HOME/lightpad.deb || error 'Failed to install lightpad.deb'
 
 rm -f ~/lightpad.deb
 
@@ -22,5 +14,4 @@ Exec=com.github.libredeb.lightpad
 Comment=LightPad is a lightweight, simple and powerful application launcher
 Categories=Accessories;Utility;
 Terminal=false" > ~/.local/share/applications/lightpad.desktop
-
 
diff --git a/apps/Min Browser/install-32 b/apps/Min Browser/install-32
--- a/apps/Min Browser/install-32
+++ b/apps/Min Browser/install-32
@@ -1,16 +1,8 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 version='1.21.0'
 rm -f ~/min.deb
 wget -O ~/min.deb https://github.com/chunky-milk/minbrowser-arm-builds/releases/download/${version}/min_${version}_armhf.deb || error "Failed to download Min deb file!"
 
-"${DIRECTORY}/pkg-install" "$HOME/min.deb" "$(dirname "$0")" || error "Failed to install min deb file!"
+install_packages $HOME/min.deb || error "Failed to install min deb file!"
 rm -f version='1.21.0'
 rm -f ~/min.deb
diff --git a/apps/Pycharm CE/install b/apps/Pycharm CE/install
--- a/apps/Pycharm CE/install
+++ b/apps/Pycharm CE/install
@@ -1,19 +1,10 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 #Defining Variables
-downloadlink=https://download.jetbrains.com/python/pycharm-community-2021.2.2.tar.gz
+downloadlink=https://download-cf.jetbrains.com/python/pycharm-community-2021.2.1.tar.gz
 name=pycharm-community
 
 # Get dependencies
-"${DIRECTORY}/pkg-install" "python3-pip openjdk-11-jdk gcc" "$(dirname "$0")" || exit 1
-
+install_packages python3-pip openjdk-11-jdk gcc || exit 1
 echo "Downloading $(basename "$downloadlink")"
 rm -f $name.tar.gz
 wget $downloadlink -O $name.tar.gz || error "Failed to download $(basename "$downloadlink")"
@@ -24,13 +15,11 @@ sudo mkdir -p /opt/$name
 sudo tar xvzf $name.tar.gz -C /opt/$name || error "Failed to extract $name.tar.gz"
 rm -f $name.tar.gz
 sudo mv /opt/$name/*/* /opt/$name/
-
 echo "Making file executable"
 sudo chmod +x /opt/$name/bin/pycharm.sh
-
 echo "Implementing terminal fix"
 rm -rf ~/pty4j
-git clone https://github.com/JetBrains/pty4j.git ~/pty4j || error "Failed to download pty4j repository"
+git_clone https://github.com/JetBrains/pty4j.git ~/pty4j || error "Failed to download pty4j repository"
 cd ~/pty4j/native
 gcc -fPIC -c *.c || error "command failed: gcc -fPIC -c *.c"
 gcc -shared -o libpty.so *.o || error "command failed: gcc -shared -o libpty.so *.o"
@@ -38,7 +27,6 @@ sudo mkdir -p /opt/$name/lib/pty4j-native/linux/arm || error "Failed to make dir
 sudo cp libpty.so /opt/$name/lib/pty4j-native/linux/arm || error "Failed to copy $(pwd)/libpty.so to /opt/$name/lib/pty4j-native/linux/arm"
 rm -rf ~/pty4j
 cd ~/
-
 echo "Creating desktop shortcut"
 echo "[Desktop Entry]
 Type=Application
diff --git a/apps/QEMU/install-64 b/apps/QEMU/install-64
--- a/apps/QEMU/install-64
+++ b/apps/QEMU/install-64
@@ -1,19 +1,10 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 #Remove any qemu packages first to prevent conflicting packages
 sudo apt purge -yqq qemu* &>/dev/null
-
 rm -f ~/qemu.deb
 #Download QEMU
 wget -O ~/qemu.deb https://github.com/chunky-milk/qemu-arm-builds/releases/download/6.0.50/qemu-6.0.50-arm64.deb || error 'Failed to Download QEMU!'
 
 #Install QEMU
-"${DIRECTORY}/pkg-install" "$HOME/qemu.deb" "$(dirname "$0")" || error 'Failed to install qemu.deb!'
+install_packages $HOME/qemu.deb || error 'Failed to install qemu.deb!'
 rm -f ~/qemu.deb
diff --git a/apps/Snap Store/install b/apps/Snap Store/install
--- a/apps/Snap Store/install
+++ b/apps/Snap Store/install
@@ -1,16 +1,6 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 # Get dependencies
-"${DIRECTORY}/pkg-install" "libsquashfuse0 squashfuse fuse libgconf-2-4" "$(dirname "$0")" || error "Failed to install libsquashfuse0 squashfuse fuse"
-sudo apt install -y snapd || error "APT failed to install snapd"
-
+install_packages libsquashfuse0 squashfuse fuse libgconf-2-4 snapd || error "Failed to install libsquashfuse0 squashfuse fuse"
 sudo systemctl enable --now snapd.socket || error "Unable to enable snapd.socket"
 sudo systemctl start snapd.service
 if [ $? != 0 ];then
@@ -19,21 +9,16 @@ if [ $? != 0 ];then
   systemctl status snapd.service
   exit 1
 fi
-
 sudo snap refresh
 sudo systemctl restart snapd.service || error "Unable to restart snapd.service"
-
 sudo modprobe squashfs || error "▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
 Failed to run sudo modprobe squashfs!
-
 Something is wrong with your kernel. If your kernel was upgraded, please reboot.
 
 Otherwise, try reinstalling the kernel using this command:
 sudo apt install --reinstall raspberrypi-bootloader raspberrypi-kernel
-
 See this forum thread: https://raspberrypi.org/forums/viewtopic.php?t=262963
 ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲"
-
 sudo snap install core18 || error "Snapd was unable to install core18"
 sudo snap install core || error "Snapd was unable to install core"
 sudo snap install snapd || error "Snapd was unable to install snapd"
@@ -42,9 +27,7 @@ sudo ln -s /var/lib/snapd/snap /snap
 
 echo "Output of 'snap version':"
 snap version
-
 sudo snap install snap-store || error "Unable to install snap store"
 sudo rm -rf /usr/share/applications/snap
 ln -s /var/lib/snapd/desktop/applications /usr/share/applications/snap || sudo ln -s /var/lib/snapd/desktop/applications /usr/share/applications/snap || error "Failed to create symlink for Snap app shortcuts!"
-
 
diff --git a/apps/Sysmon/install b/apps/Sysmon/install
--- a/apps/Sysmon/install
+++ b/apps/Sysmon/install
@@ -1,30 +1,18 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 # Get dependencies
-"${DIRECTORY}/pkg-install" "python3 python3-pip" "$(dirname "$0")" || exit 1
-
+install_packages python3 python3-pip || exit 1
 cd /opt
 rm -rf ./sysmon || sudo rm -rf ./sysmon || error "Failed to first remove $(pwd)/sysmon folder!"
-git clone https://github.com/t0xic0der/sysmon || sudo git clone https://github.com/t0xic0der/sysmon || error "Failed to clone Sysmon git repository!"
+git_clone https://github.com/t0xic0der/sysmon || sudo git_clone https://github.com/t0xic0der/sysmon || error "Failed to clone Sysmon git repository!"
 cd sysmon
 sudo pip3 install -r requirements.txt || error "Failed to install requirements with Pip!"
 
 echo "[Unit]
 After=network.target
-
 [Service]
 ExecStart=sudo python3 /opt/sysmon/main.py -p 6969 -6
-
 [Install]
 WantedBy=default.target" | sudo tee /etc/systemd/system/WebStationSYSMON.service >/dev/null
-
 #start the service
 sudo systemctl daemon-reload || error "Failed to run systemctl daemon-reload!"
 sudo systemctl enable WebStationSYSMON.service || error "Failed to enable sysmon service!"
diff --git a/apps/Timeshift/install-64 b/apps/Timeshift/install-64
--- a/apps/Timeshift/install-64
+++ b/apps/Timeshift/install-64
@@ -1,13 +1,5 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 rm -f ~/timeshift.deb
 wget -O ~/timeshift.deb https://github.com/teejee2008/timeshift/releases/download/v20.11.1/timeshift_20.11.1_arm64.deb || error 'Failed to download timeshift!'
-"${DIRECTORY}/pkg-install" "$HOME/timeshift.deb" "$(dirname "$0")" || error 'Failed to install .deb file!'
+install_packages $HOME/timeshift.deb || error 'Failed to install .deb file!'
 rm -f ~/timeshift.deb
diff --git a/apps/Turbowarp/install-32 b/apps/Turbowarp/install-32
--- a/apps/Turbowarp/install-32
+++ b/apps/Turbowarp/install-32
@@ -1,16 +1,7 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
 rm -f ~/turbowarp.deb
-wget -O ~/turbowarp.deb https://github.com/TurboWarp/desktop/releases/download/v0.10.1/TurboWarp-linux-armv7l-0.10.1.deb || error "Failed to download deb!"
-
-"${DIRECTORY}/pkg-install" "$HOME/turbowarp.deb" "$(dirname "$0")" || error "Failed to install turbowarp.deb!"
+wget -O ~/turbowarp.deb  https://github.com/TurboWarp/desktop/releases/download/v0.9.0/TurboWarp-linux-armv7l-0.9.0.deb || error "Failed to download deb!"
+install_packages $HOME/turbowarp.deb || error "Failed to install turbowarp.deb!"
 
 rm -f ~/turbowarp.deb
 
@@ -18,7 +9,6 @@ echo -n "Moving menu launcher from Education to Programming category... "
 sudo sed -i 's/Categories=Education;/Categories=Application;Development;/g' /usr/share/applications/turbowarp-desktop.desktop
 sudo sed -i 's/%U/%f%U/g' /usr/share/applications/turbowarp-desktop.desktop
 echo done
-
 #create scratch project mime type
 echo -n "Creating .sb3 mimetype... "
 sudo bash -c 'echo "<?xml version="\""1.0"\"" encoding="\""UTF-8"\""?>
@@ -31,7 +21,6 @@ sudo bash -c 'echo "<?xml version="\""1.0"\"" encoding="\""UTF-8"\""?>
 </mime-info>" > /usr/share/mime/packages/sb3.xml'
 sudo update-mime-database /usr/share/mime
 echo done
-
 if [ -z "$(cat ~/.config/mimeapps.list | grep 'turbowarp-desktop.desktop')" ];then
   echo -n "Associating the .sb3 mimetype with TurboWarp... "
   echo "[Added Associations]
diff --git a/apps/Ulauncher/install b/apps/Ulauncher/install
--- a/apps/Ulauncher/install
+++ b/apps/Ulauncher/install
@@ -1,16 +1,6 @@
 #!/bin/bash
-
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
-
 rm -f ~/ulauncher.deb
-wget -O ~/ulauncher.deb 'https://github.com/Ulauncher/Ulauncher/releases/download/5.14.0/ulauncher_5.14.0_all.deb' || error 'Failed to download ulauncher.deb!'
-
-"${DIRECTORY}/pkg-install" "gir1.2-appindicator3-0.1 python3-distutils-extra python3-levenshtein python3-websocket $HOME/ulauncher.deb" "$(dirname "$0")" || error "Failed to install ulauncher.deb and dependencies!"  
+wget -O ~/ulauncher.deb 'https://github.com/Ulauncher/Ulauncher/releases/download/5.13.0/ulauncher_5.13.0_all.deb' || error 'Failed to download ulauncher.deb!'
+install_packages gir1.2-appindicator3-0.1 python3-distutils-extra python3-levenshtein python3-websocket $HOME/ulauncher.deb || error "Failed to install ulauncher.deb and dependencies!"  
 
 rm -f ~/ulauncher.deb
diff --git a/updater b/updater
--- a/updater
+++ b/updater
@@ -19,7 +19,7 @@ get_date() {
 check_update_interval() { #return 0 if update-interval allows update-checking today, exit 1 otherwise
   local lastupdatecheck="$(cat "${DIRECTORY}/data/last-update-check" 2>/dev/null)"
   if [ -z $lastupdatecheck ];then
-    warning "${DIRECTORY}/data/last-update-check does not exist!" 1>&2
+    echo "Warning: ${DIRECTORY}/data/last-update-check does not exist!" 1>&2
     lastupdatecheck=0
   fi
   
@@ -44,9 +44,9 @@ check_update_interval() { #return 0 if update-interval allows update-checking to
   elif [ "$updateinterval" == 'Always' ];then
     return 0
   elif [ -z "$updateinterval" ];then
-    warning "Something isn't right. Does '${DIRECTORY}/data/settings/Check for updates' exist?" 1>&2
+    echo "Something isn't right. Does '${DIRECTORY}/data/settings/Check for updates' exist?" 1>&2
   else
-    echo -e "\e[91mUnrecognized update interval! \e[0m" 1>&2
+    echo "Warning: Unrecognized update interval!" 1>&2
   fi
   
   return 0
@@ -188,7 +188,7 @@ list_updates_gui() { #input: updatable_apps and updatable_files variables
   #echo "List: ${LIST}EOL"
   
   if [ -z "$LIST" ];then
-    status_green "mNothing to update. Nothing to do!"
+    echo -e '\e[92mNothing to update. Nothing to do!\e[39m'
     exit 0
   fi
   
@@ -217,15 +217,14 @@ update_now_gui() { #input: updatable_files and updatable_apps variables
     mkdir -p "$(dirname "${DIRECTORY}/${file}")"
     
     #copy new version
-    cp -f "${DIRECTORY}/update/pi-apps/${file}" "${DIRECTORY}/${file}" || echo -e "\e[91mFailed to copy ${DIRECTORY}/update/pi-apps/${file}! \e[0m"
+    cp -f "${DIRECTORY}/update/pi-apps/${file}" "${DIRECTORY}/${file}" || echo -e "\e[91mFailed to copy ${DIRECTORY}/update/pi-apps/${file}\e[39m!"
     
     #special edge-case: if current file ends in .c, delete the corresponsing executable so that it will be recompiled.
     if [[ "$file" == *.c ]];then
       rm -f "${DIRECTORY}/$(echo "$file" | sed 's/\.c$//g')"
     fi
     
-    echo
-    status_green "${file} file was copied successfully."
+    echo -e "\e[92m${file} file was copied successfully.\e[39m"
   done
   IFS="$PREIFS"
   
@@ -249,7 +248,7 @@ update_now_gui() { #input: updatable_files and updatable_apps variables
   rm -rf "${DIRECTORY}/.git" || sudo rm -rf "${DIRECTORY}/.git" || error "Failed to delete old ${DIRECTORY}/.git folder!"
   cp -a "${DIRECTORY}/update/pi-apps/.git" "${DIRECTORY}" || error "Failed to copy new .git folder!"
   
-  status_green "\nPi-Apps updates complete.\n"
+  echo -e "\e[92mPi-Apps updates complete.\e[39m"
 }
 
 update_now_cli() { #input: updatable_files and updatable_apps variables
@@ -259,14 +258,14 @@ update_now_cli() { #input: updatable_files and updatable_apps variables
     mkdir -p "$(dirname "${DIRECTORY}/${file}")"
     
     #copy new version
-    cp -f "${DIRECTORY}/update/pi-apps/${file}" "${DIRECTORY}/${file}" || echo -e "\e[91mFailed to copy ${DIRECTORY}/update/pi-apps/${file}! \e[0m"
+    cp -f "${DIRECTORY}/update/pi-apps/${file}" "${DIRECTORY}/${file}" || echo -e "\e[91mFailed to copy ${DIRECTORY}/update/pi-apps/${file}\e[39m!"
     
     #special edge-case: if current file ends in .c, delete the corresponsing executable so that it will be recompiled.
     if [[ "$file" == *.c ]];then
       rm -f "${DIRECTORY}/$(echo "$file" | sed 's/\.c$//g')"
     fi
     
-    status_green "${file} file was copied successfully."
+    echo -e "\e[92m${file} file was copied successfully.\e[39m"
   done
   
   for app in $updatable_apps ;do
@@ -277,7 +276,7 @@ update_now_cli() { #input: updatable_files and updatable_apps variables
   rm -rf "${DIRECTORY}/.git" || sudo rm -rf "${DIRECTORY}/.git" || error "Failed to delete old ${DIRECTORY}/.git folder!"
   cp -a "${DIRECTORY}/update/pi-apps/.git" "${DIRECTORY}" || error "Failed to copy new .git folder!"
   
-  status_green "\nPi-Apps updates complete."
+  echo -e "\e[92mPi-Apps updates complete.\e[39m"
 }
 
 screen_width="$(xrandr | grep "HDMI-1" | awk '{print $4}' | tr 'x+' ' ' | awk '{print $1}')"
@@ -297,19 +296,19 @@ fi
 
 #runmode values: autostarted, get-status, set-status, gui, gui-yes, cli, cli-yes
 
-status "\nUpdater mode: $runmode\n"
+echo "Updater mode: $runmode"
 if [ "$runmode" == autostarted ];then #if update-interval allows, and one app installed, display notification on boot
   
   #check if update interval allows update-checks, otherwise exit
   check_update_interval
   if [ $? != 0 ];then
-    status "Won't check for updates today, because of the update interval is set to '$(cat "${DIRECTORY}/data/settings/Check for updates")' in Settings."
+    echo "Won't check for updates today, because of the update interval is set to '$(cat "${DIRECTORY}/data/settings/Check for updates")' in Settings."
     exit 0
   fi
   
   #check that at least one app has been installed by the user
   if [ "$(ls "${DIRECTORY}/data/status" | wc -l)" == 0 ];then
-    status "No apps have been installed yet, so exiting now."
+    echo "No apps have been installed yet, so exiting now."
     exit 0
   fi
   
@@ -317,11 +316,11 @@ if [ "$runmode" == autostarted ];then #if update-interval allows, and one app in
   updatable_files="$(get_updatable_files)"
 
   if [ -z "$updatable_files" ] && [ -z "$updatable_apps" ];then
-    status "Nothing is updatable."
+    echo "Nothing is updatable."
     exit 0
   fi
   
-  status "Displaying notification in lower-right of screen..."
+  echo "Displaying notification in lower-right of screen..."
   { #display notification in lower-right
     output="$(yad --form --text='Pi-Apps updates available.' --separator='\n' \
       --on-top --skip-taskbar --undecorated --close-on-unfocus \
@@ -364,7 +363,7 @@ if [ "$runmode" == autostarted ];then #if update-interval allows, and one app in
   
   list_updates_gui
   if [ -z "$updatable_files" ] && [ -z "$updatable_apps" ];then
-    status "User did not allow anything to be updated."
+    echo "User did not allow anything to be updated."
     exit 0
   fi
   
@@ -401,16 +400,13 @@ elif [ "$runmode" == gui ];then #dialog-list of updatable apps, with checkboxes 
   updatable_files="$(get_updatable_files)"
   
   if [ -z "$updatable_files" ] && [ -z "$updatable_apps" ];then
-    status "Nothing is updatable."
+    echo "Nothing is updatable."
     exit 0
   fi
   
-  echo
-  
   list_updates_gui
   if [ -z "$updatable_files" ] && [ -z "$updatable_apps" ];then
-    status "User did not allow anything to be updated."
-    echo
+    echo "User did not allow anything to be updated."
     exit 0
   fi
   
@@ -424,7 +420,7 @@ elif [ "$runmode" == gui-yes ];then #update now without asking for confirmation
   updatable_files="$(get_updatable_files)"
   
   if [ -z "$updatable_files" ] && [ -z "$updatable_apps" ];then
-    status "Nothing is updatable."
+    echo "Nothing is updatable."
     exit 0
   fi
   
@@ -434,83 +430,50 @@ elif [ "$runmode" == cli ];then #return list of updatable apps, and ask the user
   
   updatable_apps="$(get_updatable_apps)"
   updatable_files="$(get_updatable_files)"
-  echo 
   
   if [ -z "$updatable_files" ] && [ -z "$updatable_apps" ];then
-    status "Nothing is updatable."
+    echo "Nothing is updatable."
     exit 0
   fi
   
-  if [ -z "$updatable_apps" ];then
-    status "No apps is updatable."
-    echo
-  else
-    status "These apps can be updated:"
-    echo
-    echo "$updatable_apps" | sed 's/^/  - /g'
-    echo
-  fi
+  echo "These apps can be updated:"
+  echo -n "$updatable_apps" | sed 's/^/  - /g'
+  echo
   
-  if [ -z "$updatable_files" ];then
-    status "No files is updatable"
-    echo
-  else
-    status "These files can be updated:"
-    echo
-    echo "$updatable_files" | sed 's/^/  - /g'
-    echo
-  fi
+  echo "These files can be updated:"
+  echo -n "$updatable_files" | sed 's/^/  - /g'
+  echo
   
-  read -p "$(status 'Update now? [Y/n] ')" answer
+  read -p "Update now? [Y/n] " answer
   
   if [ "$answer" == n ] || [ "$answer" == N ];then
-    echo
-    echo "Exiting now."
-    echo
     exit 0
   fi
   
-  echo
   update_now_cli
   
 elif [ "$runmode" == cli-yes ];then #update now without asking for confirmation
   
   updatable_apps="$(get_updatable_apps)"
   updatable_files="$(get_updatable_files)"
-  echo 
   
   if [ -z "$updatable_files" ] && [ -z "$updatable_apps" ];then
-    status "Nothing is updatable."
+    echo "Nothing is updatable."
     exit 0
   fi
   
-  if [ -z "$updatable_apps" ];then
-    status "No apps is updatable."
-    echo
-  else
-    status "These apps can be updated:"
-    echo
-    echo "$updatable_apps" | sed 's/^/  - /g'
-    echo
-  fi
+  echo "These apps can be updated:"
+  echo -n "$updatable_apps" | sed 's/^/  - /g'
   
-  if [ -z "$updatable_files" ];then
-    status "No files is updatable"
-    echo
-  else
-    status "These files can be updated:"
-    echo
-    echo "$updatable_files" | sed 's/^/  - /g'
-    echo
-  fi
-  
+  echo "These files can be updated:"
+  echo -n "$updatable_files" | sed 's/^/  - /g'
   echo
+  
   update_now_cli
   
 else
-  error "updater: unknown run mode. Exiting now.\n"
+  error "updater: unknown run mode."
 fi
 
-echo 
 exit 0
 } #prevents errors if script was modified while in use
